// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gduypsnquqyqcrzdslln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdXlwc25xdXF5cWNyemRzbGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDc3NzAsImV4cCI6MjA2NTgyMzc3MH0.GeWGT09Lpe8LttQGFhYSCYVBZApcMoMOqJrMFEPz_jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);